### ISSUE TITLE
Remove XML-Doc warnings

### ISSUE THREAD

**Issue by griestopf** [FUSEEProjectTeam/Fusee#106]
from 
- [x] `Fusee.Math.Core`
- [x] `Fusee.Base.Core` mainly in `AsyncHttpAsset`
- [x] `Fusee.Engine.Common` mainly in `OpenGLPrimitiveType` enum
- [x] `Fusee.Engine.Core` mainly in `SceneRenderer`
- [x] `Fusee.Engine.GUI` mainly in ` AncorPos` flag enum
- [x] `Fusee.Serialization`

**Comment by RedImp1470** [comment]
Done by merging #138 and #155 into develop
