### ISSUE TITLE
Clean-up Low-Level Shader handling within user-accessible code

### ISSUE THREAD

**Issue by griestopf** [FUSEEProjectTeam/Fusee#118]
FUSSE Apps use SetShaderEffect ONLY to set shaders.

- [x] Remove [`RenderContext.SetShader`](https://github.com/FUSEEProjectTeam/Fusee/blob/develop/src/Engine/Core/RenderContext.cs#L1163)
- [x] Remove [`ShaderProgram._rci`](https://github.com/FUSEEProjectTeam/Fusee/blob/develop/src/Engine/Core/ShaderProgram.cs#L17)
- [x] Remove any querying of shader params from non-rc-implementation code as in the [`ShaderProgram` constructor](https://github.com/FUSEEProjectTeam/Fusee/blob/develop/src/Engine/Core/ShaderProgram.cs#L34)

**Comment by RedImp1470** [comment]
Probably related to #130
