### ISSUE TITLE
Enable Deferred Rendering for WASM

### ISSUE THREAD

**Issue by RedImp1470** [FUSEEProjectTeam/Fusee#119]
DR currently doesn't work due to to "FrameBufferIncompleteAttachment" or "FrameBufferMissingAttachment" errors, occuring in the SetRenderTarget methods.
Possible reasons are incorrect or unsupported color formats when creating the textures as well as unsupported FramebufferSlots (e.g. DepthAttachment24) and other (yet unknown) differences form "es" to "core".

**Comment by RedImp1470** [comment]
**[Android]**

OpenTK 30ES does not seem to support other PixelInternalFormats other than Rgba, Rgb, Alpha, Luminance, even though OpenGL 30es seems to do so (https://www.khronos.org/registry/OpenGL-Refpages/es3.0/html/glTexImage2D.xhtml). After some research it seems the OpenTK 30es branch suffers due to the development of OpenTK 40es....

Furthermore it doesn't seem possible to attach a depth texture to a framebuffer as DEPTH_ATTACHMENT, therefore we need to render the depth into a COLOR_ATTACHMENT and create a depth render-buffer.  This is bound to create a overhead.

**Comment by wrestledBearOnce** [comment]
- [ ] Check if geometry shader work
- [ ] Check if it is safe to default to `webgl2-compute` context and check if compute shader work
