### ISSUE TITLE
Embed FUSEE into WPF application

### ISSUE THREAD

**Issue by darcome** [FUSEEProjectTeam/Fusee#125]
Hi all,

just a simple question: is it possible to embed FUSEE into a WPF app?

Thanks in advance

**Comment by griestopf** [comment]
Yes, though it might be a bit tricky. There are several ways to accomplish this. Probably the easiest way would be to use the [built-in rendering window](https://github.com/FUSEEProjectTeam/Fusee/blob/develop/src/Engine/Imp/Graphics/Desktop/RenderCanvasImp.cs#L734) that's created to host a Fusee application (your own class derived from [`RenderCanvas`](https://fusee3d.org/xref/html/T_Fusee_Engine_Core_RenderCanvas.htm)) and make this window a parent window of some WPF-control based on 
[`HwndHost`](https://docs.microsoft.com/de-de/dotnet/api/system.windows.interop.hwndhost?view=netframework-4.8) in your application. Embedding FUSEE would then be very similar to [Hosting a Win32 Control in WPF](https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/walkthrough-hosting-a-win32-control-in-wpf). One thing you need to to here is to gain access to  the RenderWindow's HWND generated by FUSEE. 

To do this you could try to [find](https://www.pinvoke.net/default.aspx/user32/FindWindow.html) the render window handle by the window caption that you previously set (See the [`Caption` property](https://fusee3d.org/xref/html/P_Fusee_Engine_Common_IRenderCanvasImp_Caption.htm) of the `IRenderCanvasImp` you [inject on startup](https://github.com/FUSEEProjectTeam/Fusee/blob/develop/Examples/Complete/Simple/Desktop/Main.cs#L52).

Another approach would be to inject a tweaked `IRenderCanvasImp` rendering on a hidden window (or even not to a window at all) and grab the generated image (from a render target texture or the hidden window`s contents each frame and blit it to some WPF control.
