### ISSUE TITLE
Duplicate Code in F.E.Player.Desktop and fuseeCmdLine

### ISSUE THREAD

**Issue by ASPePeX** [FUSEEProjectTeam/Fusee#127]
fuseeCmdLine uses mostly the same code for `fusee player` as F.E.Player.Desktop. This should be merged if possible.

- F.E.Player.Desktop: https://github.com/FUSEEProjectTeam/Fusee/blob/b133136b83d45e7c904d4a3eb9101718e920e558/src/Engine/Player/Desktop/Main.cs#L24L153
- fuseeCmdLine: https://github.com/FUSEEProjectTeam/Fusee/blob/b133136b83d45e7c904d4a3eb9101718e920e558/src/Tools/fuseeCmdLine/Program.cs#L181L310

**Comment by griestopf** [comment]
Will be fixed with #368
