### ISSUE TITLE
Implement Shard-based Shader Effects

### ISSUE THREAD

**Issue by RedImp1470** [FUSEEProjectTeam/Fusee#130]
TODO:
- [x] Implement ``SurfaceShader``
- [x] Code review for ``SurfaceShader`` as of May
- [x] Test version as of May
~Enable Bone Animation~ (moved to new Issue #252)
- [x] Implement simple Emissive term as "color added after computing all the other lighting terms" - but without impact on the surrounding scene.
- [x] Find solution for "Texture Path <-> Texture Object" problem (Serialization Tests, FusSceneConverter).  
Suggestion: Texture objects should store a path/asset-name. When back-converting use this information to generate the texture file/path. If no such information is present the back-conversion will invent a random texture name.
- [x] Transfer BRDF (#225) ``FusMaterial`` Classes from ``feature\brdf`` to ``feature\shader_shards``

**Comment by griestopf** [comment]
[FuShaderConcept.zip](https://github.com/FUSEEProjectTeam/Fusee/files/4293625/FuShaderConcept.zip)
