### ISSUE TITLE
Implement Kabsch algorithm in Fusee.Math

### ISSUE THREAD

**Issue by wrestledBearOnce** [FUSEEProjectTeam/Fusee#143]
Implement [Kabsch](https://en.wikipedia.org/wiki/Kabsch_algorithm
) algorithm in Fusee.Math and [SVD](https://en.wikipedia.org/wiki/Singular_value_decomposition) along the way.

**Comment by wrestledBearOnce** [comment]
Use case e.g.: [Finding optimal rotation and translation between corresponding 3D points](http://nghiaho.com/?page_id=671)

**Comment by wrestledBearOnce** [comment]
ref "Least-squares estimation of transformation parameters between two point patterns", Shinji Umeyama, PAMI 1991, DOI: 10.1109/34.88573

**Comment by RedImp1470** [comment]
Currently not needed
