### ISSUE TITLE
.net Core Tiered Compilation seems to cause lags

### ISSUE THREAD

**Issue by RedImp1470** [FUSEEProjectTeam/Fusee#150]
[EDIT]: 
See [https://github.com/dotnet/runtime/issues/13196](https://github.com/dotnet/runtime/issues/13196) 
A provisionally fix seems to be to disable Tired Compilation.

If Tired Compilation is **on** it can be observed ([Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon)) that the process creates a lot of threads:

![grafik](https://user-images.githubusercontent.com/9215439/73859625-9bf43f80-483a-11ea-9ccf-410dacd27b1d.png)

[EDIT]: I quickly tested it with a fixed velocity and no lags occured. May be an issue of the Input Implementation.

~~At the moment this is primarily used in TransformComponent.Rotate and TransformComponent.RotateAround.~~

**Comment by RedImp1470** [comment]
Further observations showed that the lags are not particulary related to the Mouse Input.
More lags can be observed if the frame rate is lower - disableling VSync "cures" the lags in most cases.

**Comment by griestopf** [comment]
Fixed as long as Tiered Compilation stays off.
