### ISSUE TITLE
Get Blender install dir from registry

### ISSUE THREAD

**Issue by ASPePeX** [FUSEEProjectTeam/Fusee#151]
An alternate or aditional way to find the Blender install dir is the uninstall information in the registry.

Installer:
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{053A73FE-DBF8-4674-8EC0-63BD07615695}`

Steam:
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Steam App 365670`

**Comment by griestopf** [comment]
Replaced by #337
