### ISSUE TITLE
Improve Fusee.Test.Render.Desktop

### ISSUE THREAD

**Issue by ASPePeX** [FUSEEProjectTeam/Fusee#156]
- [x] Make F.Example.AdvancedUI use a seed for testing to always produce the same result.
- [x] Make F.Example.SimpleDefered work

- [x] Calculate a distance between colors to make pixel comparison more accurate.

**Comment by RedImp1470** [comment]
Blocked by #157

**Comment by griestopf** [comment]
Maybe https://github.com/richzhang/PerceptualSimilarity could be used for image comparison?
