### ISSUE TITLE
'BoneComponent.Name' hides inherited member 'SceneComponentContainer.Name'

### ISSUE THREAD

**Issue by ASPePeX** [FUSEEProjectTeam/Fusee#158]
This results in a CS0108 warning: 'BoneComponent.Name' hides inherited member 'SceneComponentContainer.Name'. Use the new keyword if hiding was intended.

https://github.com/FUSEEProjectTeam/Fusee/blob/dab8af0255951326ff908baf609ef0bb6e505442/src/Serialization/BoneComponent.cs#L17

Can we fix this without breaking serialization? Otherwise we should fix it in the upcoming bulk of serialization changes.

**Comment by griestopf** [comment]
Yes I already saw it in the upcoming V2 serialization and will fix it.

**Comment by griestopf** [comment]
Suppressed warning CS0108 using `#pragma`
