### ISSUE TITLE
Should Resize() be marked as deprecated?

### ISSUE THREAD

**Issue by ASPePeX** [FUSEEProjectTeam/Fusee#159]
I think depending on the progress of the camera/projection things we should mark Resize as deprecated.

https://github.com/FUSEEProjectTeam/Fusee/blob/7ed90005e1ffd268d2ce16684e7bd7a083de56e9/src/Engine/Core/RenderCanvas.cs#L231

**Comment by griestopf** [comment]
We can mark it as `[Obsolete]`. What's the effect of marking to-be-overridden virtual methods as obsolete? It only makes sense if users overrding it receive a compiler warning.

**Comment by ASPePeX** [comment]
Yes, the user receives a warning when the virtual method is marked as `[Obsolete]`.

**Comment by RedImp1470** [comment]
What is the reason to mark it as deprecated? As I understand our concept at the moment, Resize() affects the application window size. The camera viewport (given in percent) only defines the part of the window this camera renders into. 
I would keep it, so a user can overwrite it to do some custom stuff he wants to do if the window is resized.

**Comment by griestopf** [comment]
I Agree to RedImp1470: Let's keep the possibility to get notified about window size changes but let's NOT use this functionality in the camera (or other scene rendering) implementation. Thus I'd like to NOT mark it as `[obsolete]`.
