### ISSUE TITLE
Check if we need to add WASM/Web functionality to fusee publish -web

### ISSUE THREAD

**Issue by griestopf** [FUSEEProjectTeam/Fusee#190]
Questions

- Do we still need `fusee publish --web | --desktop` or can this be accomplished by `dotnet build | publish` ?
- What about Android?

**Comment by wrestledBearOnce** [comment]
dotnet build works for web. To answer the first question: We do not need fusee publish anymore.

As Xamarin comes with VS and not with .NET core (yet), the task is unable to find the Xamarin build targets within the `$(MSBuildExtensionsPath)` which points to `C:\dotnet\...Xamarin` when invoking the `dotnet build` command.
However, while using VS to build it points to the (correct) path, `C:\Visual Studio\...\Xamarin`

@ASPePeX we could implement some magic build task logic which tries to use the correct path?

**Comment by ASPePeX** [comment]
If the build configuration is properly setup for D/R-Desktop and D/R-Wasm there should not be anything that uses Xamarin targets. D/R-Android or Debug/Release itself can only be build with msbuild.

**Comment by wrestledBearOnce** [comment]
> If the build configuration is properly setup for D/R-Desktop and D/R-Wasm there should not be anything that uses Xamarin targets.

That's currently the case 👍 

> D/R-Android or Debug/Release itself can only be build with msbuild.

Bummer. I thought maybe we could "trick" it to build it anyhow 😉

**Comment by ASPePeX** [comment]
The build tools (msbuild) are available even without Visual Studio: https://aka.ms/buildtools
So it isn't entirely impossible, but I'd rather wait until .NET 5. Afaik preview 3 is supposed to have Xamarin support and should drop soon.

**Comment by ASPePeX** [comment]
Preview 3 doesn't have Xamarin support :/

**Comment by wrestledBearOnce** [comment]
In conclusion:

We do not need fusee --web anymore. Android should be fine with 5.0 rc1.
