### ISSUE TITLE
Texture lookup for fus-files only in base Assets folder

### ISSUE THREAD

**Issue by ASPePeX** [FUSEEProjectTeam/Fusee#202]
When loading fus-files the ShaderCodeBuilder automatically tries to load the linked textures (https://github.com/FUSEEProjectTeam/Fusee/blob/develop/src/Engine/Core/ShaderCodeBuilder.cs#L864). But only the filename arrives at the LoadTexture(path) method, so it only loads the texture from the base of the Assets folder. Expected behavior would be loading the texture from the same folder as the fus-file.

**Comment by griestopf** [comment]
Make asset references inside .fus files (such as a referenced texture) relative to the folder inside the asset storage where the .fus file resides. Example 

Assets/
   -  Subfolder/
          - Model.fus (references Texture "Image.png")
          - Image.png (is in the same subfolder as Model.fus)
