### ISSUE TITLE
Check and replace System.Math methods with M.cs methods if cast to double is needed, , implement if necessary

### ISSUE THREAD

**Issue by wrestledBearOnce** [FUSEEProjectTeam/Fusee#203]
## Method requires cast

- [ ] sin
- [ ] asin
- [ ] cos
- [ ] acos
- [ ] tan
- [ ] atan
- [ ] atan2
- [ ] pow
- [x] abs
- [ ] ~~static PI~~
- [ ] sqrt
- [ ] log
- [ ] ceiling
- [ ] max
- [ ] min
- [ ] sign
- [ ] round

# Replaced methods

- [ ] abs

**Comment by RedImp1470** [comment]
Done (#330)
