### ISSUE TITLE
Xirkit conversion tests fail when executing all tests at once.

### ISSUE THREAD

**Issue by qogoist** [FUSEEProjectTeam/Fusee#217]
When executing all Xirkit tests at once some of the conversion tests will fail seemingly at random.
This is not the case when only the conversion tests are being run.

Might be due to a race-condition when multiple test classes are trying to access the [conversion dictionary](https://github.com/FUSEEProjectTeam/Fusee/blob/develop/src/Xirkit/PinFactory.cs#L191).

**Comment by griestopf** [comment]
Should be solved by putting the converision dictionary inititalization into a [static constructor](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/static-constructors) which [seem to be threadsafe](https://stackoverflow.com/questions/7095/is-the-c-sharp-static-constructor-thread-safe)

If that's not enough, using a [`lock` statement](https://docs.microsoft.com/en-us/dotnet/csharp/language-
reference/keywords/lock-statement) around a lock object instantiated inside a static constructor should do the job.
