### ISSUE TITLE
Headless mode - Rendering without graphic context

### ISSUE THREAD

**Issue by ArnaudVall** [FUSEEProjectTeam/Fusee#266]
Hello,

Thanks for your work on this project ! realy great

I'm looking for a possibility to create a simple scene and to render it to a picture on a server without any visible surface.
Is there a possibility to do that with Fusee ?

thanks in advance for your answer
Arnaud

**Comment by ASPePeX** [comment]
Yes but it is not really tested at the moment and probably broken for a lot of environments.

We are trying to use a headless mode for our render tests (they render out images and compare them pixel by pixel to a reference: https://github.com/FUSEEProjectTeam/Fusee/tree/master/src/Tests/Render/Desktop). This used to work on GitHub Actions and Azure Pipelines, but is broken for both services as for now and I'm not entirely sure why.

One important thing is that you need have to a fitting OpenGL library depending on your environment. Here is an example how OpenTK does it: https://github.com/opentk/opentk/blob/master/install-opengl.ps1

I'm sorry that I can't give you a definitive answer on this, but if you decide to try it I would be interested in any feedback you can provide.

**Comment by ArnaudVall** [comment]
Hi ASPePeX

I finaly switched to BabylonJS associated with a headleass chrome (Puppeteer) to generate pictures
Thanks for your feedback 

Kind regards
Arnaud
