### ISSUE TITLE
Add WikiPage describing AABB

### ISSUE THREAD

**Issue by griestopf** [FUSEEProjectTeam/Fusee#271]
- [x] Describe usage of AABB class
- [x] Provide one or more examples
- [ ] optional: Developer notes

**Comment by Simon-Za** [comment]
https://github.com/FUSEEProjectTeam/Fusee/wiki/Axis-Aligned-Bounding-Box

**Comment by griestopf** [comment]
After reviewing, some things to change

- [ ] Remove table of "Components". Instead link to the API documentation: https://fusee3d.org/api/Fusee.Math.Core.AABBf.html. 
- [ ] If after removing the table still relevant: Use the correct spelling of **frustum** (it's NOT frust**r**um)
- [ ] Instead of the table add example sections for the most relevant methods (illustrated with images if possible):
     -  Intersects (another AABB or a single point)
     - Union
     - InsideOrIntersectingPlane
     - InsideOrIntersectingFrustum

**Comment by Simon-Za** [comment]
https://github.com/FUSEEProjectTeam/Fusee/wiki/Axis-Aligned-Bounding-Box
