### ISSUE TITLE
Error when trying to load asset into scene

### ISSUE THREAD

**Issue by Simon-Za** [FUSEEProjectTeam/Fusee#273]
System.Reflection.TargetInvocationException: 'Exception has been thrown by the target of an invocation.'

Two Inner Exceptions:
1. Exception: Error while compiling shader for pass 0
2. NullReferenceException: Object reference not set to an instance of an object.

It seems the shader is missing from the asset, blender materials consist only of Diffuse BSDF, did not work with only Principled BSDF either.

[Trench1new.zip](https://github.com/FUSEEProjectTeam/Fusee/files/5546331/Trench1new.zip) fus file

[Trench1new.zip](https://github.com/FUSEEProjectTeam/Fusee/files/5547087/Trench1new.zip) blend file

**Comment by griestopf** [comment]
Just tested on my current working branch (blender_addon_animation):

![Trench1newScrennshot](https://user-images.githubusercontent.com/1692092/99376855-c85ae300-28c5-11eb-8413-9b9718a0ed43.PNG)

Seems to work there. What FUSEE version are you working on? Are you using NUGET or a self-compiled version of FUSEE?

**Comment by Simon-Za** [comment]
I'm on Version 0.8.2.0 using NuGet.
It worked in my player too but not as asset import in my scene.

**Comment by griestopf** [comment]
Is reproducable in Fusee player in version 0.9.0. The crash occurs due to the Diffuse BSDF materials used in the blender file at [FusSeneConverter.cs, line 397](https://github.com/FUSEEProjectTeam/Fusee/blob/master/src/Engine/Core/FusSceneConverter.cs#L397) . When changing all materials to Principled BSDF no crash happens.

**Comment by Simon-Za** [comment]
Updating to 0.9.0 fixed the problem, thank you
