### ISSUE TITLE
Exception when loading cube car model exported from blender.

### ISSUE THREAD

**Issue by griestopf** [FUSEEProjectTeam/Fusee#279]
Steps to reproduce
- Install FUSEE 0.9.0 & Blender Exporter
- Convert attached CubeCar.blend (contained in [CubeCar.zip](https://github.com/FUSEEProjectTeam/Fusee/files/5581771/CubeCar.zip)) to .fus
- Load resulting .fus as an asset

Error occurs also when trying to display the resulting .fus file in FUSEE Player

**Comment by ASPePeX** [comment]
It seams to be a problem with the Diffuse BSDF shader import or export. When I change the shaders to Principled BSDF it works. I started fixes in hotfix/ShaderLoading and prevented it from crashing but haven't found the source bug yet.

**Comment by ASPePeX** [comment]
The Diffuse BSDF shader comes in as FusMaterialBase. That seems to be missing its corresponding visitor in SceneConverter.

**Comment by RedImp1470** [comment]
We haven't implemented [Diffuse BSDF](https://docs.blender.org/manual/en/latest/render/shader_nodes/shader/diffuse.html) and [Glossy BSDF](https://docs.blender.org/manual/en/latest/render/shader_nodes/shader/glossy.html) properly in the Blender exporter an on the FUSEE side. I'm going to fix this in the hotfix/ShaderLoading branch.

**Comment by RedImp1470** [comment]
Fixed via #283
