### ISSUE TITLE
Interpret RenderContext.ClearColor in linear color space

### ISSUE THREAD

**Issue by griestopf** [FUSEEProjectTeam/Fusee#280]
Color values in float4 should be interpreted in linear color space throughout FUSEE. Make commands such as

```C#
RC.ClearColor = (float4) ColorUint.LightGreen;
```
work as expected. Add (Linear -> sRGB) conversion in the setter and (sRGB -> Linear) in the getter of ClearColor.

**Comment by RedImp1470** [comment]
Fixed via #283
