### ISSUE TITLE
Website improvement

### ISSUE THREAD

**Issue by Jonathan-Schnee** [FUSEEProjectTeam/Fusee#281]
- [x] Navbar is too short on some pages because the text on the page is too long
- [x] Margin around the rocket in the Navbar with expanded menu as well as with burger menu.
- [x] Examples have incorrect GitHub links. 
    - Add "disclaimer" at top of page: "This page shows some examples of our upcoming Web Assembly support enabling FUSEE applications to run in web browsers".
    - Fix links to point to "develop_wasm" branch, e. g. [Simple](https://github.com/FUSEEProjectTeam/Fusee/tree/develop_wasm/Examples/Complete/Simple/WebAsm)
- [x] Some pictures in wiki do not exist / are not displayed
    - List of wiki pages with missing pictures.
              - Getting FUSEE and getting started / First Steps
              - General Information / Code Documentation Workflow
- [x] Resize FUSEE logo width on home page to 30%
- [x] "Improve this doc" link on right side:
   - Link is broken on Wiki pages (probably due to the fact that the Website repo is a submodule
   - Link seems to work on page unter Api Documentation
   - Todo: Can we remove the "Improve this Doc" completely?
- [x] Replace [PLACEHOLDER](https://fusee3d.org/api/index.html) Api Documentation main page. 
- [x] Wiki Pages
     - [x] List pages with awkward Tab names due to inappropriate first heading contents
         - General Information / Overall Project Structure
         - General Information / Code Documentation Workflow
         - General Information / Git flow
         - General Information / Update External Projects
         - General Information / Editing Website

         - Getting FUSEE and getting started / Using FUSEE in Visual Studio Code
         - Getting FUSEE and getting started / Getting Started
         - Getting FUSEE and getting started / First Steps
         - Getting FUSEE and getting started / First Steps Scene Management
         - Getting FUSEE and getting started / Input and Input Devices
         - Getting FUSEE and getting started / FUSEE in diffrent Browsers (locally)

         -  Building the Engine / How FUSEE Builds

         - Using FUSEE / The Rendering Pipeline / Multipass Rendering -quick start guide
         - Using FUSEE / The Rendering Pipeline / Deferred Rendering
         - Using FUSEE / Camera
         - Using FUSEE / Textures / Texture types and their usage
         - Using FUSEE / Textures / Using videos as texture
         - Using FUSEE / Animation / Keyframe Animation
         - Using FUSEE / The Particle System / Setup the Particle System 

     - [x] List pages with hand-generated "On this page" overview headers within in the page
         - General Information / Overall Project Structure

         - Getting FUSEE and getting started / Getting Started
         - Getting FUSEE and getting started / Input and Input Devices

         -  Building the Engine / How FUSEE Builds

         - Using FUSEE / Miscellianeous / Logging

     - [x] List pages that don't have automatically generated "In this article" overview link-list/menu at the right margin.
         - General Information / Overall Project Structure
         - General Information / Code Documentation Workflow
         - General Information / Git flow
         - General Information / Update External Projects

         - Getting FUSEE and getting started / Getting Started
         - Getting FUSEE and getting started / First Steps
         - Getting FUSEE and getting started / First Steps Scene Management
         - Getting FUSEE and getting started / Input and Input Devices

         -  Building the Engine / How FUSEE Builds

         - Using FUSEE / Textures / Using videos as texture

     - Find out the rule when DocFx generates "In this article" margins and when not.

Currently not fixed
- [ ] Footer is not displayed on some phones. -> Not reproducable on dev's mobile phone.

- [ ] Wiki Menu "Using Fusee" too confusing on phones: Third-level Table-of-contents entries are placed confusingly on screen. -> Could only be fixed by flattening all Table-of-contents entries which would result in too much scrolling.

- [ ] Can DocFx recognize the `NamespaceDoc` classes describing the entire namespace? If yes, how can we control displaying its contents instead of or in combination with the DocFX-auto-generated namespace Api Doc pages? -> After a long search there is no way to insert the namespaces.

**Comment by wrestledBearOnce** [comment]
![image](https://user-images.githubusercontent.com/4386896/100104644-c0bbb100-2e66-11eb-9c2a-27e5c6ad16fe.png)

Some margin around the rocket inside the header would be nice 😉
