### ISSUE TITLE
Concept for point cloud rendering

### ISSUE THREAD

**Issue by griestopf** [FUSEEProjectTeam/Fusee#318]
Evaluate current research state and asses different approaches on how to integrate them in FUSEE.

https://www.cg.tuwien.ac.at/research/publications/2020/SCHUETZ-2020-MPC/
https://arxiv.org/pdf/2104.07526.pdf
https://github.com/potree/PotreeConverter

**Comment by RedImp1470** [comment]
**As is:**

- **Preprocessing Tool** that can handle a few million points with acceptable RAM and time usage
- **App** that can read "Out of Core" Files and render the point cloud
- **App** is not compatible with deferred rendering and the latest changes in shader handling in FUSEE right now
   - E.g. it cannot use SurfaceEffects
- **Compute Shader**: first "beta" implementation in feature/ComputeShaders
- No sophisticated point cloud rendering without preprocessing and LOD data structure (Octree)
   - This may be a problem if we ever want to support "live preview" features

**Research advances:**

- **Preprocessing Tool**
   - [PotreeConverter 2.0](https://github.com/potree/PotreeConverter) (C++) can handle a lot more points
   - Uses a new file structure and an optimized Octree
   - Licensed [under 2-clause BSD](https://github.com/potree/PotreeConverter/blob/develop/LICENSE)

- **Rendering**
   - Usage of ComputeShaders to improve the rendering performance
   - Usage of sorting algorithms to improve the rendering performance
   - Good rendering performance (of large point clouds) without LOD data structure and preprocessing

**Comment by griestopf** [comment]
First step: Concentrate on Rendering of un-pre-processed point clouds using ComputeShaders in FUSEE.
Get a grasp how to integrate ComputeShader rendered results with classically rendered results regarding
- z-integration
- using common rendering states, especially MVP-matrices
-
