### ISSUE TITLE
Fix OpenGL Debug warnings

### ISSUE THREAD

**Issue by griestopf** [FUSEEProjectTeam/Fusee#320]
In deferred rendering OpenGL repeatedly reports "undefined behavior".

[openGLDebugCallback():101] Program undefined behavior warning: The current GL state uses a sampler (0) that has depth comparisons enabled, with a texture object (30) with a depth format, by a shader that samples it with a non-shadow sampler. This will result in undefined behavior
        id:131222 severity:DebugSeverityMedium type:DebugTypeUndefinedBehavior source:DebugSourceApi

**Comment by wrestledBearOnce** [comment]
Fixed with: #327
