### ISSUE TITLE
Mesh(Component)

### ISSUE THREAD

**Issue by ASPePeX** [FUSEEProjectTeam/Fusee#35]
Remove MeshComponent. Use new Mesh type instead and  move to Fusee.Serialization, also inherit SceneComponent container. Remove MeshComponentMap from SceneRenderer.

**Comment by CoffeeParser** [comment]
Fixed in master.
MeshComponent removed.
SerializeData.py reworked.
Old *.fus files need to be replaced with new ones because the *.fus Format changed incompatible.
