### ISSUE TITLE
Use a camera in instead of view/projection matrix calculation 

### ISSUE THREAD

**Issue by RedImp1470** [FUSEEProjectTeam/Fusee#379]
Use Camera component in all Examples (including tutorials) and in Player
Add a "no scene graph" example directly setting camera values on RC

- [ ] Tutorials
- [x] "No-Scene-Graph"-Example added

**Complete Examples**

- [x] Player
- [x] AdvancedUI
- [x] ~~BoneAnimation~~ Removed, because bone animation is not supported right now
- [x] Camera
- [x] ~~ComputeFractal~~
- [x] Deferred
- [x] GeometryEditing
- [x] Integrations
- [x] Labyrinth
- [x] Materials
- [x] MeshingAround
- [x] Picking
- [x] PointCloudLive
- [x] PointCloudOutOfCore
- [x] RenderLayer
- [x] Simple
- [x] _Delete_ Starkiller
- [x] ThreeDFont
- [x] UI

**Comment by griestopf** [comment]
Tutorials handled by #449
