### ISSUE TITLE
Make ShaderEffect  a ressource type managed by RenderContext

### ISSUE THREAD

**Issue by griestopf** [FUSEEProjectTeam/Fusee#39]
- [x] Add RenderContext.SetShaderEffect(ShaderEffect se)
- [x] Remove all RenderContext/GPU specific stuff from ShaderEffect internals
- [x] Add Changed/Disposed event to ShaderEffect 
- [x] Add Lookup table to RenderContext to keep track of already allocated shaders for a given RenderContext
- [x] Find a way to handle 1:n relationship between ShaderEffect and Shaders
- [x] Move ShaderEffect.RenderMesh functionality to RenderContext.Render(Mesh m) and remove ShaderEffect.RenderMesh
- [x] Find a more typed way for implementing ShaderEffect.SetEffectParam / GetEffectParam
- [x] ADVANCED: inherit ShaderEffect from DynamicObject and make all declared parameters
dynamic properties such that shader parameters can be set by myShaderEffect.MyCustomParam = xyz;
- [x] Debug repeated RenderContextImp.CreateShader calls
- [x] Avoid unnecessary OpenGL set uniform parameter calls
- [x] Experiment: Try dynamic with nuget package in player.cs
- [x] Compare value update: float4x4 compare
- [x] Documentation
- [x] BugFixes in Examples!

**Comment by moritzhfu** [comment]
Experiment: Upgrade all portable projects to .net standart 2.0

**Comment by moritzhfu** [comment]
Bug: When a custom shadereffect is used, SceneRenderer tries to set the value of the default lightcomponent which results in endless warnings.

**Comment by moritzhfu** [comment]
Hierarchy broken.

**Comment by moritzhfu** [comment]
Fixed: https://github.com/FUSEEProjectTeam/Fusee/commit/6c7ce4420de9304a9052e8ee46b68dcd859e4cf9
