### ISSUE TITLE
Unify Math Double and Float classes

### ISSUE THREAD

**Issue by griestopf** [FUSEEProjectTeam/Fusee#418]

**Comment by RedImp1470** [comment]
**Fusee.Math.Core**
- [x] double2
- [x] double3
- [x] double4
- [x] double3x3
- [x] double4x4
- [x] AABBd
- [x] OBBd
- [x] RayD
- [x] QuaternionD
- [x] Eigen (the Diagonalizer suffers from floating-point errors, therefore the float version was removed for now)
- [ ] FrustumD
- [ ] PlaneD

**Fusee.Tests.Math.Core**
- [x] double2
- [x] double3
- [x] double4
- [x] double3x3
- [x] double4x4
- [ ] AABBd
- [x] OBBd
- [ ] RayD
- [x] QuaternionD
- [x] Eigen (the Diagonalizer suffers from floating-point errors, therefore the float version was removed for now)
- [ ] FrustumD
- [ ] PlaneD
