### ISSUE TITLE
Engine cannot be built on macOS

### ISSUE THREAD

**Issue by LucasRitter** [FUSEEProjectTeam/Fusee#44]
When attempting to build the Fusee.Engine project from the master branch, Fusee.Serialization will stop as soon as the PrecompileTool gets executed.

OS: macOS 10.13.4
Mono: 5.10.0.160
IDE: Rider 2018.1 181.4952.142

![image](https://user-images.githubusercontent.com/20494846/39982637-4e236d58-5755-11e8-99d2-29305efc0cf9.png)
![image](https://user-images.githubusercontent.com/20494846/39982670-6023e302-5755-11e8-9fd1-4e869224be6a.png)

**Comment by griestopf** [comment]
Thanks for the report. Unfortunately, currently only a few individuals contribute to the project, so the MAC build is poorly supported. I never gave Rider a try so far - didn't expect it to get this far anyway.
