### ISSUE TITLE
Mesh does not recalculate its BoundingBox when changed.

### ISSUE THREAD

**Issue by ASPePeX** [FUSEEProjectTeam/Fusee#456]
... it should.

**Comment by RedImp1470** [comment]
Seems to be fixed: [https://github.com/FUSEEProjectTeam/Fusee/blob/master/src/Engine/Core/MeshManager.cs#L79](https://github.com/FUSEEProjectTeam/Fusee/blob/master/src/Engine/Core/MeshManager.cs#L79)

**Comment by RedImp1470** [comment]
see #605
