### ISSUE TITLE
Remove RenderContext from ScenePicker

### ISSUE THREAD

**Issue by griestopf** [FUSEEProjectTeam/Fusee#510]
Unify ScenePicker and RaycastPicker. In general, RenderContext should be avoided. Projection and View Matrices should be set by cameras. Avoid multiple camera pre passes per frame.

Use RenderContext only for render traversal. Other traversal types (picking) must not use render context. Otherwise traversal will run into issues if more than one render traversal was performed and a third traversal relies on the state of the first render traversal.

**Comment by wrestledBearOnce** [comment]
See #670
