### ISSUE TITLE
Fusee.Serialization should be able to find the path to mscorlib.dll for netstandard.

### ISSUE THREAD

**Issue by ASPePeX** [FUSEEProjectTeam/Fusee#57]
Fusee.Serialization uses a static path to the netstandard2.0 mscorlib.dll.
Either:

1. Update the precompiler so it can find netstandard and netcoreapp
2. Update the SerializationCompileSerializer build step to find the correct path and pass it to the precompiler.

**Comment by valerysntx** [comment]
How the native library dll should be resolved ? #https://github.com/dotnet/core-setup/pull/4301/ 
Does the .csproj [re-organisation ](https://github.com/dotnet/core-setup/blob/9a776be820ff4ae83476c7e9e97514ecd8f3ae1d/Documentation/design-docs/DotNetCore-SharedPackageStore.md#net-core---shared-package-store) should be made, like multi-target and port to .netstandard2.0,
I beleive all will grow the complexity, so starting from clear evidence of wrong dll reference, - how this could be tested ?
```    
 [DllImport("mscorelib.dll", CharSet = CharSet.Unicode, ExactSpelling = true, CallingConvention = CallingConvention.Cdecl)]
// PInvoke wrapper could be made for tests
```
