### ISSUE TITLE
ImGuiFilePicker: "Cancel" button is clipped

### ISSUE THREAD

**Issue by RedImp1470** [FUSEEProjectTeam/Fusee#576]
Seems to get worse with increasing font size:
![image](https://user-images.githubusercontent.com/9215439/181520959-37f0b3b6-903e-4e3f-a710-c1087760bc77.png)
![image](https://user-images.githubusercontent.com/9215439/181521054-acd3bccb-3553-4189-965c-352c8ba66b51.png)

**Comment by wrestledBearOnce** [comment]
Disabled fixed width of the “Selected file”-text-input. This re-enabled the automatic spacing. Should work again.

**Comment by wrestledBearOnce** [comment]
Latest fix (pre-calculate needed width for buttons and input text)

![grafik](https://user-images.githubusercontent.com/4386896/182346194-56d86f78-841c-4d00-8962-c8f06bd6360f.png)

![grafik](https://user-images.githubusercontent.com/4386896/182346689-0f95c43b-0056-4452-9a24-f547077657fc.png)

![grafik](https://user-images.githubusercontent.com/4386896/182346822-f6e38e4c-877f-44d2-88b8-08da0cc43495.png)
