### ISSUE TITLE
SharpFont/Freetype dependencies are Debug

### ISSUE THREAD

**Issue by ASPePeX** [FUSEEProjectTeam/Fusee#58]
In Fusee.Base.Imp.Android and Fusee.Base.Imp.Desktop the references for SharpFont and Freetype are all to debug libraries.

**Comment by griestopf** [comment]
The reason for our self-compiled version fo Freetype is that I could not find any FreeType repository capable of generating FreeType binaries for Android from a VS solution (using CLANG). It would be great to get around this hack.

**Comment by ASPePeX** [comment]
Added freetype release libraries https://github.com/FUSEEProjectTeam/Fusee/commit/5b65586d27d6c4b2b31b8a6bfd1c4865539dbc1c
