### ISSUE TITLE
Create a Point Cloud Mesh type

### ISSUE THREAD

**Issue by griestopf** [FUSEEProjectTeam/Fusee#610]
The Point Cloud Mesh type mapping (more or less) 1:1 the point data and attributes as defined in the potree point type.

**Comment by wrestledBearOnce** [comment]
Note: If I read the source code correctly, the `Potree point type` contains all `LAZ`-attributes, if necessary.

See: https://github.com/potree/PotreeConverter/blob/develop/Converter/include/PotreeConverter.h#L136

and some other places, where these values are being saved and converted. Therefore, we should discuss which types we want to support, too

**Comment by wrestledBearOnce** [comment]
@wrestledBearOnce creates a laz file with all attributes

**Comment by ASPePeX** [comment]
Obsolete since #622
