### ISSUE TITLE
fuseeCmdLine does not honor the correct JSIL settings when building a template build for web.

### ISSUE THREAD

**Issue by ASPePeX** [FUSEEProjectTeam/Fusee#62]
A Fusee web build from a template crashes when using Linq (probably others things too). Linq is used in out picking implementation.
This also initialy happened when I switched the platform to netstandard2.0, the fix was excluding `System.Linq` in the dead code analysis of JSIL (https://github.com/FUSEEProjectTeam/Fusee/commit/18f4fb128acf9aa407845b42a5618f889cdb5331).
This is happening again when building a template with `fusee publish --platform Web`.

How to reproduce:
* Create a new fuse template project `dotnet new fusee`
* Add some picking to it.
* `fusee publish --platform Web`

**Comment by griestopf** [comment]
@RedImp1470 already worked on a similar issue (maybe the same?). The fix was to hand-code missing Linq-Functions in JavaScript.

**Comment by ASPePeX** [comment]
It works when I replace the code in Fusee.Engine.Player.Core with the code that wasn't working for the template. So I think there is something going wrong in the toolchain for the templates.
It also looks like the same bug I had for Fusee.Engine.Example.Picking until I updated defaults.jsilconfig (https://github.com/FUSEEProjectTeam/Fusee/commit/18f4fb128acf9aa407845b42a5618f889cdb5331).

**Comment by ASPePeX** [comment]
No longer relevant since we dropped JSIL.
