### ISSUE TITLE
Transform.cs should have guards and noexcept

### ISSUE THREAD

**Issue by wrestledBearOnce** [FUSEEProjectTeam/Fusee#630]
We do not want to have any `NaN`s or `Infinity` nor any exceptions.

**Comment by wrestledBearOnce** [comment]
Should `Fusee.Math` include `Fusee.Core` for error messages?

**Comment by RedImp1470** [comment]
See https://github.com/FUSEEProjectTeam/Fusee/pull/631#pullrequestreview-1107158889

**Comment by wrestledBearOnce** [comment]
https://github.com/FUSEEProjectTeam/Fusee/issues/594
