### ISSUE TITLE
System.OverflowException if Geometry in a .fus file is too large

### ISSUE THREAD

**Issue by ASPePeX** [FUSEEProjectTeam/Fusee#64]
Protobuf runs into a System.OverflowException if the geometry in a .fus file is too large.
Example code at https://github.com/FUSEEProjectTeam/Fusee-Bug-SerializationOverflow

**Comment by ASPePeX** [comment]
Turns out that we only allow `ushort[]` for triangles in Mesh.cs line 223-243.
The bug in this case is that it just explodes instead of handling the exception gracefully.

**Comment by griestopf** [comment]
A decent .fus exporter would partition an input mesh into chunks each not exceeding the 65k limit for vertex indices. The good old C4D exporter handled this...

**Comment by wrestledBearOnce** [comment]
Is this still a thing with the new protobuf scheme?
ref: #92
