### ISSUE TITLE
Blender exporter does not apply all tansformations befor exporting.

### ISSUE THREAD

**Issue by ASPePeX** [FUSEEProjectTeam/Fusee#65]
When the attached file is imported to blender and then exported to .fus, the geometry in Fusee is upside down even tho it looks correct in Blender.

This can be fixed in Blender by [Apply Object Transformations](https://docs.blender.org/manual/en/dev/editors/3dview/object/editing/transform/clear_apply.html#bpy-ops-object-transform-apply)

The Blender exporter should do this by itself to avoid confusing the user.

[points_uniform_mesh_supertiny_uv2.zip](https://github.com/FUSEEProjectTeam/Fusee/files/2510049/points_uniform_mesh_supertiny_uv2.zip)

**Comment by griestopf** [comment]
The attached .obj file has all normals facing towards the inside. Added `bmesh.ops.recalc_face_normals(bm, faces=bm.faces)` to the Blender-AddOn corrects the converted model.
