### ISSUE TITLE
Remaining work for Potree2 file access

### ISSUE THREAD

**Issue by wrestledBearOnce** [FUSEEProjectTeam/Fusee#659]
- [ ] Make Reader and Writer static again -> Readers and Writers should be able to process a infinite number of Files at runtime.
- [x] Fix writers position and color conversion.
- [ ] Documentation

**Comment by wrestledBearOnce** [comment]
see: https://github.com/FUSEEProjectTeam/Fusee/issues/455

**Comment by ASPePeX** [comment]
Conversion in 31aa47ccf5660a44cef36db7c5ee123c672ddb6a
