### ISSUE TITLE
Re-visit `ImGui.Input`

### ISSUE THREAD

**Issue by wrestledBearOnce** [FUSEEProjectTeam/Fusee#664]
Currently the `ImGuiInputDriver` is very bare bone and not production ready.

Re-iterate and implement with different keyboard layouts (and languages) and input vs. UTF-8 text output in mind. 

@griestopf it would be nice if we could meet and discuss how to achieve a clean and good implementation. We could use something like this: https://stackoverflow.com/a/47409469 (`GetEncoding()`) alternatively `Char.Parse(char, CultureInfo)`.

**Comment by griestopf** [comment]
Also look at https://github.com/FUSEEProjectTeam/Fusee/issues/651
Also look at how Z/Y are (mis-) handled on English/German keyboard layout

**Comment by RedImp1470** [comment]
![Image](https://user-images.githubusercontent.com/9215439/196697959-75daf36c-35b4-4013-8ce8-87ebc9346913.png)
