### ISSUE TITLE
Re-Visit ScenePicker

### ISSUE THREAD

**Issue by wrestledBearOnce** [FUSEEProjectTeam/Fusee#670]
Implement `ScenePicker` anew.

- Merge `RayCastPicking` with `OctantPicker` and the 'old' `ScenePicker` into one `ScenePicker` Visitor.
- Add `PickingSceneNode` with `Picking-Layers` and the possibility to provide a custom `Pick()` method 

### Requirements 

- Detect and work with geometry shader
- Detect and work with non-triangle geometry (`PrimitiveType.Line` et al.)
- One picker for all (including point cloud picking)
- Provide the possibility to filter (same mechanism as render layer)
- Use `Transform` matrices (implement billboard without a custom shader) (picking should therefore always work regardless if screen-space or world space)
- Provide custom picking method for user implemented shader
- Use ray-cast picker instead of "reverse" picker where possible
- Provide the possibility for per-point-picking (render based?, compute shader based?)
- Picker should have no knowledge of the `RC`
- Unit tests
- Documentation

### Implementation

- Implement modular picker (named `ScenePicker`) 
   - [x] Visitor with State (no `RC`)
   - Differentiate and call method for each case:
      - Normal geometry (mesh with triangles) <- default
      - Non-triangle geometry and/or geometry shader
      - Point cloud
- [x] Implement pick component (bump serialization to v.2)
  - Provides 'visibility' functionality similar to the render layer implementation
  - For non-standard case: provide possibility to pass/depot own picking method for this and all child components
- [x] Provide polymorphic PickResult
  - Minimal implementation: z sorting, reference on object (with type)
- [ ] Unit Tests
    - [ ] V2 Serialization (V2.FusPickComp & V2.FusMesh)
    - [ ] V2 Serialization with Python (does namespace work?)
    - [ ] PickComponent (with custom method)
    - [ ] ScenePicker

### Misc

- Rename `RaycastPicker` to `Raycaster`
- Remove picking functionality
- Keep basic functionality (return all elements a ray would hit from a given world starting position in a specific direction)

**Comment by wrestledBearOnce** [comment]
Blocked by https://github.com/FUSEEProjectTeam/POLAR/issues/147

**Comment by griestopf** [comment]
TODO: CPU-based Point Cloud Picking.
