### ISSUE TITLE
`ImGuiFilePicker`: Copy paste of folder does not update SelectedFolder/CurrentOpenFolder

### ISSUE THREAD

**Issue by wrestledBearOnce** [FUSEEProjectTeam/Fusee#745]
Happens with `OnlyAllowFolders`

![image](https://user-images.githubusercontent.com/4386896/226655015-60ba9d43-daef-4b38-881b-b88396c50d17.png)

**Comment by RedImp1470** [comment]
Something is off here:


![Image](https://user-images.githubusercontent.com/9215439/236795284-919c186b-76ea-4569-97bc-3e433135da78.png)

When `OnlyAllowFolders = true` `OnPicked` shouldn't need the `selectedFile`.
Also check `if`clause for plausability.
