### ISSUE TITLE
Fusee Android crashes during multitasking, app switching

### ISSUE THREAD

**Issue by wrestledBearOnce** [FUSEEProjectTeam/Fusee#81]
## Steps to reproduce:

- Android 8.1
- VS 2017

Start a Fusee app, change to another app (e.g. browser), try to change back to Fusee app.

```
Unhandled Exception:

System.NotSupportedException: Unable to activate instance of type
 Fusee.Engine.Imp.Graphics.Android.RenderCanvasGameView
 from native handle 0xff9280dc (key_handle 0x74c98a).

04-13 13:24:44.342 I/zygote  (14207): Thread[3,tid=14213,WaitingInMainSignalCatcherLoop,
Thread*=0xe638fc00,peer=0x12d80088,"Signal Catcher"]: reacting to signal 3
04-13 13:24:44.342 I/zygote  (14207): 
04-13 13:24:44.525 I/zygote  (14207): Wrote stack traces to '[tombstoned]'
```

Possible problem (?):

> The problem is this: for better or worse, virtual method calls from constructors invoke the most derived method implementation.

From here: [https://stackoverflow.com/a/10603714](https://stackoverflow.com/a/10603714)

**Comment by ASPePeX** [comment]
The quick and easy fix is to just comment out these two lines https://github.com/FUSEEProjectTeam/Fusee/blob/46e9adcc6dfbb684b7fa131c77148cad05d3efbb/src/Engine/Imp/Graphics/Android/RenderCanvasImp.cs#L402L403. I'm not sure if this is also a good fix. ... investigating further.

**Comment by ASPePeX** [comment]
- None of the Xamarin mobile-samples (https://github.com/xamarin/mobile-samples) that use OpenGL implement any disposal, especially not on task switch.
- I could not find anything in the Xamarin documentation that disposal must be implemented for OpenGL.
- There are old forum discussions that talk about implementing this but nothing current.
- There is a seperate override for OnDispose, which is never called.

I guess this is correct then ...
